# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.18.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.18.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/tskamaldeep/CLionProjects/DASHIF-Conformance

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/tskamaldeep/CLionProjects/DASHIF-Conformance

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.18.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.18.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tskamaldeep/CLionProjects/DASHIF-Conformance/CMakeFiles /Users/tskamaldeep/CLionProjects/DASHIF-Conformance//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tskamaldeep/CLionProjects/DASHIF-Conformance/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DASHIF_Conformance

# Build rule for target.
DASHIF_Conformance: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DASHIF_Conformance
.PHONY : DASHIF_Conformance

# fast build rule for target.
DASHIF_Conformance/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/build
.PHONY : DASHIF_Conformance/fast

ConformanceConstraints.o: ConformanceConstraints.cpp.o

.PHONY : ConformanceConstraints.o

# target to build an object file
ConformanceConstraints.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/ConformanceConstraints.cpp.o
.PHONY : ConformanceConstraints.cpp.o

ConformanceConstraints.i: ConformanceConstraints.cpp.i

.PHONY : ConformanceConstraints.i

# target to preprocess a source file
ConformanceConstraints.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/ConformanceConstraints.cpp.i
.PHONY : ConformanceConstraints.cpp.i

ConformanceConstraints.s: ConformanceConstraints.cpp.s

.PHONY : ConformanceConstraints.s

# target to generate assembly for a file
ConformanceConstraints.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/ConformanceConstraints.cpp.s
.PHONY : ConformanceConstraints.cpp.s

ConformanceErrorLevels.o: ConformanceErrorLevels.cpp.o

.PHONY : ConformanceErrorLevels.o

# target to build an object file
ConformanceErrorLevels.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/ConformanceErrorLevels.cpp.o
.PHONY : ConformanceErrorLevels.cpp.o

ConformanceErrorLevels.i: ConformanceErrorLevels.cpp.i

.PHONY : ConformanceErrorLevels.i

# target to preprocess a source file
ConformanceErrorLevels.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/ConformanceErrorLevels.cpp.i
.PHONY : ConformanceErrorLevels.cpp.i

ConformanceErrorLevels.s: ConformanceErrorLevels.cpp.s

.PHONY : ConformanceErrorLevels.s

# target to generate assembly for a file
ConformanceErrorLevels.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/ConformanceErrorLevels.cpp.s
.PHONY : ConformanceErrorLevels.cpp.s

ConformanceException.o: ConformanceException.cpp.o

.PHONY : ConformanceException.o

# target to build an object file
ConformanceException.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/ConformanceException.cpp.o
.PHONY : ConformanceException.cpp.o

ConformanceException.i: ConformanceException.cpp.i

.PHONY : ConformanceException.i

# target to preprocess a source file
ConformanceException.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/ConformanceException.cpp.i
.PHONY : ConformanceException.cpp.i

ConformanceException.s: ConformanceException.cpp.s

.PHONY : ConformanceException.s

# target to generate assembly for a file
ConformanceException.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/ConformanceException.cpp.s
.PHONY : ConformanceException.cpp.s

ConformanceMPDCheckSequence.o: ConformanceMPDCheckSequence.cpp.o

.PHONY : ConformanceMPDCheckSequence.o

# target to build an object file
ConformanceMPDCheckSequence.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/ConformanceMPDCheckSequence.cpp.o
.PHONY : ConformanceMPDCheckSequence.cpp.o

ConformanceMPDCheckSequence.i: ConformanceMPDCheckSequence.cpp.i

.PHONY : ConformanceMPDCheckSequence.i

# target to preprocess a source file
ConformanceMPDCheckSequence.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/ConformanceMPDCheckSequence.cpp.i
.PHONY : ConformanceMPDCheckSequence.cpp.i

ConformanceMPDCheckSequence.s: ConformanceMPDCheckSequence.cpp.s

.PHONY : ConformanceMPDCheckSequence.s

# target to generate assembly for a file
ConformanceMPDCheckSequence.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/ConformanceMPDCheckSequence.cpp.s
.PHONY : ConformanceMPDCheckSequence.cpp.s

ConformanceMPDParser.o: ConformanceMPDParser.cpp.o

.PHONY : ConformanceMPDParser.o

# target to build an object file
ConformanceMPDParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/ConformanceMPDParser.cpp.o
.PHONY : ConformanceMPDParser.cpp.o

ConformanceMPDParser.i: ConformanceMPDParser.cpp.i

.PHONY : ConformanceMPDParser.i

# target to preprocess a source file
ConformanceMPDParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/ConformanceMPDParser.cpp.i
.PHONY : ConformanceMPDParser.cpp.i

ConformanceMPDParser.s: ConformanceMPDParser.cpp.s

.PHONY : ConformanceMPDParser.s

# target to generate assembly for a file
ConformanceMPDParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/ConformanceMPDParser.cpp.s
.PHONY : ConformanceMPDParser.cpp.s

ConformanceTestTimer.o: ConformanceTestTimer.cpp.o

.PHONY : ConformanceTestTimer.o

# target to build an object file
ConformanceTestTimer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/ConformanceTestTimer.cpp.o
.PHONY : ConformanceTestTimer.cpp.o

ConformanceTestTimer.i: ConformanceTestTimer.cpp.i

.PHONY : ConformanceTestTimer.i

# target to preprocess a source file
ConformanceTestTimer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/ConformanceTestTimer.cpp.i
.PHONY : ConformanceTestTimer.cpp.i

ConformanceTestTimer.s: ConformanceTestTimer.cpp.s

.PHONY : ConformanceTestTimer.s

# target to generate assembly for a file
ConformanceTestTimer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/ConformanceTestTimer.cpp.s
.PHONY : ConformanceTestTimer.cpp.s

library.o: library.cpp.o

.PHONY : library.o

# target to build an object file
library.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/library.cpp.o
.PHONY : library.cpp.o

library.i: library.cpp.i

.PHONY : library.i

# target to preprocess a source file
library.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/library.cpp.i
.PHONY : library.cpp.i

library.s: library.cpp.s

.PHONY : library.s

# target to generate assembly for a file
library.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/library.cpp.s
.PHONY : library.cpp.s

tests/addTimestampDetails.o: tests/addTimestampDetails.cpp.o

.PHONY : tests/addTimestampDetails.o

# target to build an object file
tests/addTimestampDetails.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/tests/addTimestampDetails.cpp.o
.PHONY : tests/addTimestampDetails.cpp.o

tests/addTimestampDetails.i: tests/addTimestampDetails.cpp.i

.PHONY : tests/addTimestampDetails.i

# target to preprocess a source file
tests/addTimestampDetails.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/tests/addTimestampDetails.cpp.i
.PHONY : tests/addTimestampDetails.cpp.i

tests/addTimestampDetails.s: tests/addTimestampDetails.cpp.s

.PHONY : tests/addTimestampDetails.s

# target to generate assembly for a file
tests/addTimestampDetails.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/tests/addTimestampDetails.cpp.s
.PHONY : tests/addTimestampDetails.cpp.s

tests/catchinit.o: tests/catchinit.cpp.o

.PHONY : tests/catchinit.o

# target to build an object file
tests/catchinit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/tests/catchinit.cpp.o
.PHONY : tests/catchinit.cpp.o

tests/catchinit.i: tests/catchinit.cpp.i

.PHONY : tests/catchinit.i

# target to preprocess a source file
tests/catchinit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/tests/catchinit.cpp.i
.PHONY : tests/catchinit.cpp.i

tests/catchinit.s: tests/catchinit.cpp.s

.PHONY : tests/catchinit.s

# target to generate assembly for a file
tests/catchinit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/tests/catchinit.cpp.s
.PHONY : tests/catchinit.cpp.s

tests/testConformanceException.o: tests/testConformanceException.cpp.o

.PHONY : tests/testConformanceException.o

# target to build an object file
tests/testConformanceException.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/tests/testConformanceException.cpp.o
.PHONY : tests/testConformanceException.cpp.o

tests/testConformanceException.i: tests/testConformanceException.cpp.i

.PHONY : tests/testConformanceException.i

# target to preprocess a source file
tests/testConformanceException.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/tests/testConformanceException.cpp.i
.PHONY : tests/testConformanceException.cpp.i

tests/testConformanceException.s: tests/testConformanceException.cpp.s

.PHONY : tests/testConformanceException.s

# target to generate assembly for a file
tests/testConformanceException.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DASHIF_Conformance.dir/build.make CMakeFiles/DASHIF_Conformance.dir/tests/testConformanceException.cpp.s
.PHONY : tests/testConformanceException.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DASHIF_Conformance"
	@echo "... ConformanceConstraints.o"
	@echo "... ConformanceConstraints.i"
	@echo "... ConformanceConstraints.s"
	@echo "... ConformanceErrorLevels.o"
	@echo "... ConformanceErrorLevels.i"
	@echo "... ConformanceErrorLevels.s"
	@echo "... ConformanceException.o"
	@echo "... ConformanceException.i"
	@echo "... ConformanceException.s"
	@echo "... ConformanceMPDCheckSequence.o"
	@echo "... ConformanceMPDCheckSequence.i"
	@echo "... ConformanceMPDCheckSequence.s"
	@echo "... ConformanceMPDParser.o"
	@echo "... ConformanceMPDParser.i"
	@echo "... ConformanceMPDParser.s"
	@echo "... ConformanceTestTimer.o"
	@echo "... ConformanceTestTimer.i"
	@echo "... ConformanceTestTimer.s"
	@echo "... library.o"
	@echo "... library.i"
	@echo "... library.s"
	@echo "... tests/addTimestampDetails.o"
	@echo "... tests/addTimestampDetails.i"
	@echo "... tests/addTimestampDetails.s"
	@echo "... tests/catchinit.o"
	@echo "... tests/catchinit.i"
	@echo "... tests/catchinit.s"
	@echo "... tests/testConformanceException.o"
	@echo "... tests/testConformanceException.i"
	@echo "... tests/testConformanceException.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

